//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uyg03Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public string UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKatId { get; set; }
        public decimal UrunFiyat { get; set; }
        public string UrunStokDurum { get; set; }
        public int UrunStokAdet { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
